### ISSUE TITLE
Plugin not supported at preview 

### ISSUE THREAD

**Issue by Kf637** [danvergara/morphos#61]
**Describe the bug**
Preview is not available, only showing "plugin not supported" 

**To Reproduce**
1. Convert PDF to JPG
2. When done, click on Download
3. At the preview it says "Plugin not supported "

**Expected behavior**
It should show a preview of the converted content

**Screenshots**
![image](https://github.com/user-attachments/assets/ee38f4f2-0321-4029-864f-adf2c3c7b0c9)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 23H2

**Additional context**
There's no errors in Docker logs and client browser. I've also tried multiple times with the same results.

**Comment by danvergara** [comment]
That's on me and it's OK. I included a preview for the initial conversions, but as I added more complex ones I had to return zip files instead of raw files and the preview is not optimized to see the content of the zip files containing multiple files. Honestly, I din't know how to preview those zip files and move on.

Let me think how to handle that situation.

**Comment by Kf637** [comment]
It's possible to make it show a message like "Preview not available" when it fails or is unable to load the preview.
